public enum ProjectType 
{
    UNKNOWN,
    
    COMPUTER_SCIENCE_FACULTY,
    ECONOMICS_FACULTY,
    LAW_FACULTY,
    
    COMPUTER_SCIENCE_BACHELOR,
    COMPUTER_SCIENCE_MASTER,
    COMPUTER_SCIENCE_SPECIALIST,
    
    ECONOMICS_BACHELOR,
    ECONOMICS_MASTER,
   
    LAW_BACHELOR,
    LAW_MASTER,
   
    
    ECONOMICS_BACHELOR_ECONOMICS_AND_ENTERPRISE,
    ECONOMICS_BACHELOR_FINANCE_AND_CREDIT,
    ECONOMICS_BACHELOR_ACCOUNTING_AND_AUDIT,
    ECONOMICS_BACHELOR_MARKETING,
    ECONOMICS_BACHELOR_INTERNATIONAL_ECONOMICS,
    
    ECONOMICS_MASTER_FINANCEFINANCE_AND_CREDIT,
    ECONOMICS_MASTER_BANKING,
    ECONOMICS_MASTER_ACCOUNTING_AND_AUDIT,
    ECONOMICS_MASTER_MARKETING, 
    
    
    LAW_MASTER_CRIMINAL,
    LAW_MASTER_CIVIL
    
};
