# Generated by Django 5.2.14 on 2026-05-22 03:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_conversation_muted_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pinned_for',
            field=models.ManyToManyField(blank=True, related_name='pinned_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
