# Generated by Django 5.2.14 on 2026-05-25 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_conversation_pinned_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hidden_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
