# Generated by Django 5.2.14 on 2026-05-26 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_message_hidden_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='unread_for',
            field=models.ManyToManyField(blank=True, related_name='unread_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
