# Generated by Django 5.2.14 on 2026-05-21 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_last_seen_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_nicknames', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nickname_set_by_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_user__username'],
                'unique_together': {('owner', 'target_user')},
            },
        ),
    ]
