"""Create fixtures table

Revision ID: 2aea3cf3e333
Revises: b61e1ba5890f
Create Date: 2026-09-09 11:53:46.270982
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = "2aea3cf3e333"
down_revision: str | Sequence[str] | None = "b61e1ba5890f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fixtures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("referee", sa.String(length=150), nullable=True),
        sa.Column("kickoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("round_name", sa.String(length=100), nullable=True),
        sa.Column("venue_api_id", sa.Integer(), nullable=True),
        sa.Column("venue_name", sa.String(length=150), nullable=True),
        sa.Column("venue_city", sa.String(length=100), nullable=True),
        sa.Column("status_long", sa.String(length=50), nullable=False),
        sa.Column("status_short", sa.String(length=10), nullable=False),
        sa.Column("elapsed", sa.Integer(), nullable=True),
        sa.Column("extra_time", sa.Integer(), nullable=True),
        sa.Column("home_goals", sa.Integer(), nullable=True),
        sa.Column("away_goals", sa.Integer(), nullable=True),
        sa.Column("halftime_home", sa.Integer(), nullable=True),
        sa.Column("halftime_away", sa.Integer(), nullable=True),
        sa.Column("fulltime_home", sa.Integer(), nullable=True),
        sa.Column("fulltime_away", sa.Integer(), nullable=True),
        sa.Column("extra_home", sa.Integer(), nullable=True),
        sa.Column("extra_away", sa.Integer(), nullable=True),
        sa.Column("penalty_home", sa.Integer(), nullable=True),
        sa.Column("penalty_away", sa.Integer(), nullable=True),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "home_team_id <> away_team_id", name="ck_fixtures_different_teams"
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
            name=op.f("fk_fixtures_away_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
            name=op.f("fk_fixtures_home_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_fixtures_season_id_seasons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixtures")),
        sa.UniqueConstraint("api_id", name=op.f("uq_fixtures_api_id")),
    )
    op.create_index(
        op.f("ix_fixtures_away_team_id"), "fixtures", ["away_team_id"], unique=False
    )
    op.create_index(
        op.f("ix_fixtures_home_team_id"), "fixtures", ["home_team_id"], unique=False
    )
    op.create_index(
        op.f("ix_fixtures_kickoff_at"), "fixtures", ["kickoff_at"], unique=False
    )
    op.create_index(
        op.f("ix_fixtures_season_id"), "fixtures", ["season_id"], unique=False
    )
    op.create_index(
        op.f("ix_fixtures_status_short"), "fixtures", ["status_short"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fixtures_status_short"), table_name="fixtures")
    op.drop_index(op.f("ix_fixtures_season_id"), table_name="fixtures")
    op.drop_index(op.f("ix_fixtures_kickoff_at"), table_name="fixtures")
    op.drop_index(op.f("ix_fixtures_home_team_id"), table_name="fixtures")
    op.drop_index(op.f("ix_fixtures_away_team_id"), table_name="fixtures")
    op.drop_table("fixtures")
    # ### end Alembic commands ###
