"""Create fixture lineups table

Revision ID: 7a69834c3986
Revises: 9c47dc026e55
Create Date: 2026-09-18 18:44:00.415964
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = "7a69834c3986"
down_revision: str | Sequence[str] | None = "9c47dc026e55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fixture_lineups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("formation", sa.String(length=20), nullable=True),
        sa.Column("coach_api_id", sa.Integer(), nullable=True),
        sa.Column("coach_name", sa.String(length=150), nullable=True),
        sa.Column("coach_photo_url", sa.String(length=500), nullable=True),
        sa.Column("colors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "starting_xi", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "substitutes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_fixture_lineups_fixture_id_fixtures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_fixture_lineups_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixture_lineups")),
        sa.UniqueConstraint(
            "fixture_id", "team_id", name="uq_fixture_lineups_fixture_id_team_id"
        ),
    )
    op.create_index(
        op.f("ix_fixture_lineups_fixture_id"),
        "fixture_lineups",
        ["fixture_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fixture_lineups_team_id"), "fixture_lineups", ["team_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fixture_lineups_team_id"), table_name="fixture_lineups")
    op.drop_index(op.f("ix_fixture_lineups_fixture_id"), table_name="fixture_lineups")
    op.drop_table("fixture_lineups")
    # ### end Alembic commands ###
