"""Create fixture statistics table

Revision ID: 9c47dc026e55
Revises: eb74bde66b42
Create Date: 2026-09-17 14:46:12.358184
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = "9c47dc026e55"
down_revision: str | Sequence[str] | None = "eb74bde66b42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fixture_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column(
            "statistics", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_fixture_statistics_fixture_id_fixtures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_fixture_statistics_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixture_statistics")),
        sa.UniqueConstraint(
            "fixture_id", "team_id", name="uq_fixture_statistics_fixture_id_team_id"
        ),
    )
    op.create_index(
        op.f("ix_fixture_statistics_fixture_id"),
        "fixture_statistics",
        ["fixture_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fixture_statistics_team_id"),
        "fixture_statistics",
        ["team_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fixture_statistics_team_id"), table_name="fixture_statistics"
    )
    op.drop_index(
        op.f("ix_fixture_statistics_fixture_id"), table_name="fixture_statistics"
    )
    op.drop_table("fixture_statistics")
    # ### end Alembic commands ###
