"""Create standings table

Revision ID: a7c75c6d69ff
Revises: 2aea3cf3e333
Create Date: 2026-09-12 12:07:22.172481
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = "a7c75c6d69ff"
down_revision: str | Sequence[str] | None = "2aea3cf3e333"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "standings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("goals_diff", sa.Integer(), nullable=False),
        sa.Column("group_name", sa.String(length=100), nullable=True),
        sa.Column("form", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("played", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("draws", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("goals_for", sa.Integer(), nullable=False),
        sa.Column("goals_against", sa.Integer(), nullable=False),
        sa.Column(
            "home_stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "away_stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "played >= 0 AND wins >= 0 AND draws >= 0 "
                "AND losses >= 0 AND goals_for >= 0 "
                "AND goals_against >= 0"
            ),
            name="ck_standings_nonnegative_stats",
        ),
        sa.CheckConstraint("position > 0", name="ck_standings_positive_position"),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_standings_season_id_seasons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_standings_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_standings")),
        sa.UniqueConstraint(
            "season_id", "team_id", name="uq_standings_season_id_team_id"
        ),
    )
    op.create_index(
        op.f("ix_standings_season_id"), "standings", ["season_id"], unique=False
    )
    op.create_index(
        op.f("ix_standings_team_id"), "standings", ["team_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_standings_team_id"), table_name="standings")
    op.drop_index(op.f("ix_standings_season_id"), table_name="standings")
    op.drop_table("standings")
    # ### end Alembic commands ###
