"""Create teams table

Revision ID: b61e1ba5890f
Revises: 96c178deb410
Create Date: 2026-09-01 16:58:20.350227
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision: str = "b61e1ba5890f"
down_revision: str | Sequence[str] | None = "96c178deb410"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=True),
        sa.Column("country_name", sa.String(length=100), nullable=True),
        sa.Column("founded", sa.Integer(), nullable=True),
        sa.Column(
            "is_national", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("api_id", name=op.f("uq_teams_api_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teams")
    # ### end Alembic commands ###
