"""Create fixture events table

Revision ID: eb74bde66b42
Revises: a7c75c6d69ff
Create Date: 2026-09-15 16:13:37.118802
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = "eb74bde66b42"
down_revision: str | Sequence[str] | None = "a7c75c6d69ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fixture_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("event_order", sa.Integer(), nullable=False),
        sa.Column("elapsed", sa.Integer(), nullable=False),
        sa.Column("extra_time", sa.Integer(), nullable=True),
        sa.Column("player_api_id", sa.Integer(), nullable=True),
        sa.Column("player_name", sa.String(length=150), nullable=True),
        sa.Column("assist_api_id", sa.Integer(), nullable=True),
        sa.Column("assist_name", sa.String(length=150), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("detail", sa.String(length=100), nullable=False),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "elapsed >= 0", name="ck_fixture_events_nonnegative_elapsed"
        ),
        sa.CheckConstraint(
            "event_order >= 0", name="ck_fixture_events_nonnegative_order"
        ),
        sa.CheckConstraint(
            "extra_time IS NULL OR extra_time >= 0",
            name="ck_fixture_events_nonnegative_extra_time",
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_fixture_events_fixture_id_fixtures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_fixture_events_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixture_events")),
        sa.UniqueConstraint(
            "fixture_id", "event_order", name="uq_fixture_events_fixture_id_event_order"
        ),
    )
    op.create_index(
        op.f("ix_fixture_events_event_type"),
        "fixture_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fixture_events_fixture_id"),
        "fixture_events",
        ["fixture_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fixture_events_team_id"), "fixture_events", ["team_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fixture_events_team_id"), table_name="fixture_events")
    op.drop_index(op.f("ix_fixture_events_fixture_id"), table_name="fixture_events")
    op.drop_index(op.f("ix_fixture_events_event_type"), table_name="fixture_events")
    op.drop_table("fixture_events")
    # ### end Alembic commands ###
