"""create body measurements table

Revision ID: d58a5868ac87
Revises: 4614e99d4580
Create Date: 2026-07-07 15:07:06.694979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58a5868ac87'
down_revision: Union[str, Sequence[str], None] = '4614e99d4580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.Date(), nullable=False),
    sa.Column('body_weight', sa.Float(), nullable=False),
    sa.Column('body_fat', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_measurements_id'), 'body_measurements', ['id'], unique=False)
    op.create_index(op.f('ix_body_measurements_measured_at'), 'body_measurements', ['measured_at'], unique=False)
    op.create_index(op.f('ix_body_measurements_user_id'), 'body_measurements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_body_measurements_user_id'), table_name='body_measurements')
    op.drop_index(op.f('ix_body_measurements_measured_at'), table_name='body_measurements')
    op.drop_index(op.f('ix_body_measurements_id'), table_name='body_measurements')
    op.drop_table('body_measurements')
    # ### end Alembic commands ###
